//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("\"Pure\" Xamarin.Forms Tabs (no renderers). Segmented control, bottombar tabs, unde" +
    "rlined tabs, scrollable tabs, badges...")]
[assembly: System.Reflection.AssemblyCompany("Sharpnado")]
[assembly: System.Reflection.AssemblyProduct("Tabs")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Sharpnado 2021")]
[assembly: System.Reflection.AssemblyFileVersion("2.1.1")]
[assembly: System.Reflection.AssemblyVersion("2.1.1")]
[assembly: System.Reflection.AssemblyTitle("Sharpnado.Tabs")]


